name: Build and Push Docker Image

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: koa-rest-api
  ECS_SERVICE: koa-rest-api-service
  ECS_CLUSTER: koa-rest-api-cluster
  ECS_TASK_DEFINITION: koa-rest-api-td

  CONTAINER_NAME: koa-rest-api

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
